#server.port=8080
#
## DataSource settings
#spring.datasource.url=jdbc:h2:mem:travel_agency;DB_CLOSE_DELAY=-1
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.show-sql=false
#
#spring.jpa.hibernate.ddl-auto=update
#spring.security.enabled=true
#
#application.security.jwt.secret-key = 404E635263336A586E3272357538782F413F4428472B4B6250645367566B5970
#application.security.jwt.expiration = 86400000
#application.security.jwt.refresh-token.expiration = 172800000
#
#org.springframework.security=DEBUG
#
#
##debug
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.data-locations=classpath:dev-data.sql
#

spring.messages.encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.messages.basename=messages
spring.messages.fallback-to-system-locale=false


server.port=8080

spring.profiles.active=dev

spring.jpa.show-sql=false
spring.security.enabled=true

application.security.jwt.secret-key=404E635263336A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=172800000

logging.level.com.epam.finaltask=DEBUG
logging.level.org.springframework.security=DEBUG

server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-exception=false
spring.output.ansi.enabled=always