spring.datasource.url=jdbc:h2:file:./data/travel_agency
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=false

spring.sql.init.mode=never